#!/bin/sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export GDK_DPI_SCALE=2

#export PLASMA_USE_QT_SCALING=1
#export QT_SCALE_FACTOR=1
#
#export QT_AUTO_SCREEN_SCALE_FACTOR=3

xrdb -load ~/.config/x11/xresources &
xmodmap -e "keycode 108 = Multi_key" &
# xmodmap -e "keycode 119 = r" &
xset r rate 200 60 & # Speed xrate up
unclutter &          # Remove mouse when idle
#transmission-daemon &
#pulseaudio &
killall pulseaudio && pulseaudio --start &
# calcurse --daemon &
# turn off the annoying middle click paste
xinput set-button-map 13 1 1 3 &
fcitx &

touchegg &
syncthing -no-browser -home="/home/zhenyu/.config/syncthing" &

xrandr_backlight & # workaround to change nvidia brightness
